---
title: "Arbeidskrav 1"
format: html
    theme: default
editor_options: 
  chunk_output_type: console
---


## Laste ned datasettet
```{r}
library(tidyverse)

data <-readxl::read_excel("./data/styrke_vo2maks_maod.xlsx")

str(data)
```


Burde bytte navn på ene variabelen.
```{r}
data <- data |> 
  rename(percent.aerob = `%.energy.aerob`) 
```


Deretter vil vi ha de fleste variablene som numeriske. 
Hvis ikke blir ikke skjønner ikke r der det er na. 

```{r}
data <- data |> 
  transform(id = as.character(id), 
            hr.max = as.numeric(hr.max), 
            `30.W` = as.numeric(`30.W`), 
            `30.N` = as.numeric(`30.N`), 
            `60.W` = as.numeric(`60.W`), 
            `60.N` = as.numeric(`60.N`), 
            `75.W` = as.numeric(`75.W`), 
            `75.N` = as.numeric(`75.N`), 
            acc.o2.consumption = as.numeric(acc.o2.consumption), 
            acc.o2.debt = as.numeric(acc.o2.debt), 
            percent.aerob = as.numeric(percent.aerob)) 
  
```


```{r}
data <- data |> 
  rename(percent.aerob = `%.energy.aerob`) 
```





